query {
  countries {
    nodes {
      id
      isoName
      iso
      iso3
      name
      numcode
      statesRequired
      createdAt
      updatedAt
      states {
        nodes {
          name
          abbr
          createdAt
          updatedAt
        }
      }
    }
  }
}
