query {
  countries {
    nodes {
      createdAt
      id
      iso
      iso3
      isoName
      name
      numcode
      states {
        nodes {
          abbr
          createdAt
          id
          name
          updatedAt
        }
      }
      statesRequired
      updatedAt
    }
  }
}
