query {
  taxonomies {
    nodes {
      createdAt
      id
      name
      updatedAt
      rootTaxon {
        children {
          nodes {
            children {
              nodes {
                id
              }
            }
            createdAt
            description
            iconUrl
            id
            metaDescription
            metaKeywords
            metaTitle
            name
            parentTaxon {
              id
            }
            permalink
            updatedAt
          }
        }
        createdAt
        description
        iconUrl
        id
        metaDescription
        metaKeywords
        metaTitle
        name
        parentTaxon {
          id
        }
        permalink
        updatedAt
      }
      taxons {
        nodes {
          children {
            nodes {
              createdAt
              description
              iconUrl
              id
              metaDescription
              metaKeywords
              metaTitle
              name
              parentTaxon {
                id
              }
              permalink
              updatedAt
            }
          }
          createdAt
          description
          iconUrl
          id
          metaDescription
          metaKeywords
          metaTitle
          name
          parentTaxon {
            id
          }
          permalink
          updatedAt
        }
      }
    }
  }
}
