query {
  currentOrder {
    id
    number
    shipments {
      nodes {
        createdAt
        number
        shippedAt
        shippingRates {
          nodes {
            cost
            createdAt
            currency
            selected
            updatedAt
          }
        }
        state
        tracking
        trackingUrl
        updatedAt
      }
    }
  }
}
