query {
  currentStore {
    cartTaxCountryIso
    code
    createdAt
    currencies {
      nodes {
        htmlEntity
        isoCode
        name
        symbol
      }
    }
    default
    defaultCurrency
    mailFromAddress
    metaDescription
    metaKeywords
    name
    seoTitle
    updatedAt
    url
  }
}
