query {
  completedOrders {
    nodes {
      id
      adjustments {
        nodes {
          __typename
          amount
          createdAt
          eligible
          label
          updatedAt
          ... on PromotionAdjustment {
            id
            promotionCode
          }
          ... on TaxAdjustment {
            id
          }
        }
      }
    }
  }
}
