query {
  completedOrders {
    nodes {
      id
      shippingAddress {
        id
        address1
        address2
        alternativePhone
        city
        company
        country {
          id
          createdAt
          iso
          iso3
          isoName
          name
          numcode
          updatedAt
        }
        id
        createdAt
        name
        phone
        state {
          id
          abbr
          name
          createdAt
          updatedAt
        }
        stateName
        updatedAt
        zipcode
      }
    }
  }
}
