query {
  taxonomies {
    nodes {
      id
      name
      createdAt
      updatedAt
      rootTaxon {
        id
      }
      taxons {
        nodes {
          id
          name
          permalink
          description
          metaTitle
          metaDescription
          metaKeywords
          iconUrl
          children {
            nodes {
              id
              name
              permalink
              description
              metaTitle
              metaDescription
              metaKeywords
              iconUrl
            }
          }
          createdAt
          updatedAt
        }
      }
    }
  }
}
